Repository lecture-developer/lecture_website_template, pull requests merged in 2020-11, with the labels that each got.

#17 New footer
  components/footer.html
  css/main.css
  img/footer/bitbucket.png
  img/footer/email.png
  img/footer/github.png
  img/footer/google.png
  img/footer/linkedin.png
  img/footer/phone.png
  img/logo.png
  js/components/icons.js
Labels: enhancement

#18 Course page creation
  course-page.html
  css/course-page.css
  data/jsons/teaching.json
  img/mdi_insert_drive_file.png
  img/mdi_slideshow.png
  img/mdi_video_library.png
  js/components/course.js
  js/components/courseModule.js
  js/components/courseResource.js
  js/components/courseUpdate.js
  js/components/tabs.js
  js/pages/course-page.js
Labels: enhancement

#21 Publication card
  css/main.css
  js/components/publicationCard.js
Labels: good first issue

#24 Research page
  css/research.css
  data/jsons/research.json
  img/research/google-scholar.png
  img/research/linkedin.png
  img/research/person-image.png
  img/research/website.png
  js/components/courseResource.js
  js/components/researchProject.js
  js/components/researchTeamMember.js
  js/pages/research.js
  research.html
Labels: enhancement

#32 research with me section ready
  css/research.css
  data/jsons/research.json
  js/components/researchPosition.js
  js/pages/research.js
  research.html
Labels: enhancement

#41 updated index icons and adresses list
  css/main.css
  index.html
  js/components/icons.js
  js/pages/index.js
Labels: bug

#40 added isFileFormat function in publicationCard
  data/jsons/index.json
  js/components/publicationCard.js
Labels: enhancement

#39 add "read more/show less" functionality in resource and research pages
  css/course-page.css
  css/research.css
  data/jsons/teaching.json
  js/components/course.js
  js/components/courseResource.js
  js/components/courseUpdate.js
  js/components/researchProject.js
  js/descriptionSlicer.js
  js/pages/course-page.js
  js/pages/research.js
Labels: enhancement

#43 fixed icons
  js/components/icons.js
Labels: bug

#46 Added search result component
  css/main.css
  search.html
Labels: enhancement

#44 About page
  about.html
  css/about.css
  css/courses.css
  css/main.css
  data/jsons/index.json
  data/jsons/lecturer.json
  data/jsons/resources.json
  data/jsons/teaching.json
  js/components/courseCard.js
  js/components/icons.js
  js/components/projectSection.js
  js/components/resources.js
  js/components/tabs.js
  js/descriptionSlicer.js
  js/pages/about.js
  js/pages/teaching.js
  teaching.html
Labels: enhancement

#42 Design fix
  404.html
  course-page.html
  css/course-page.css
  css/descriptionTrim.css
  css/main.css
  css/research.css
  css/tabs.css
  data/jsons/academic-publications.json
  data/jsons/index.json
  img/expand_more.png
  index.html
  js/components/projectPanel.js
  js/components/publicationCard.js
  js/components/researchPosition.js
  js/components/researchProject.js
  js/pages/academic-publications.js
  js/pages/course-page.js
  js/pages/index.js
  js/pages/research.js
  publications.html
  research.html
Labels: enhancement

#49 Hadar fixes
  about.html
  css/about.css
  css/courses.css
  css/main.css
  data/jsons/teaching.json
  js/components/courseCard.js
  js/descriptionSlicer.js
  js/pages/about.js
  js/pages/teaching.js
  teaching.html
Labels: bug

#54 all bugs are fixed
  about.html
  css/about.css
  css/main.css
  js/components/courseCard.js
  js/pages/about.js
  js/pages/academic-publications.js
  js/pages/teaching.js
  publications.html
Labels: bug

#55 added id for lecturer name
  components/header.html
Labels: enhancement
